import Head from 'next/head';
import Image from 'next/image';
import styled from 'styled-components';

import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Halang</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Contents>HI, I'm halang </Contents>
      </main>
    </div>
  );
}

const Contents = styled.h2`
  font-size: 2rem;
  font-weight: 700;
`;
